### ISSUE TITLE
Memory leak in cf::future::timeout

### ISSUE THREAD

**Issue by maximg** [rpz80/cf#14]
Leak sanitizer reports memory leaks in cf::future::timeout:

```
Indirect leak of 200 byte(s) in 1 object(s) allocated from:
    #0 0x7f05db14f458 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0458)
 ...
    #17 0x561efd1b9d9a in std::shared_ptr<cf::promise<int> > std::make_shared<cf::promise<int>>() /usr/include/c++/7/bits/shared_ptr.h:707
    #18 0x561efd1b9905 in cf::future<int> cf::future<int>::timeout<long, std::ratio<1l, 1l>, cf::time_watcher, std::runtime_error>(std::chrono::duration<long, std::ratio<1l, 1l> >, std::runtime_error const&, cf::time_watcher&) /home/mgv/src/cf/cf/cfuture.h:617
```
Reproducer:
```
cf::future<int> test()
{
    return cf::make_ready_future(10);
}

void test_future()
{
    cf::time_watcher tw;
    auto f = test()
                .timeout(1s, std::runtime_error("oops"), tw);
    f.get();
}
```
[memleak.log](https://github.com/rpz80/cf/files/2406099/memleak.log)

**Comment by maximg** [comment]
A memory leak is reported when the timeout is triggered as well. Will attach a reproducer and a log shortly.

**Comment by rpz80** [comment]
Thanks for the report. [Fixed](https://github.com/rpz80/cf/commit/af62f1274f70c0a7fb2c68c7366a9bb9fda9122a).

**Comment by maximg** [comment]
Thanks! Confirm that the leak is gone, also in the timeout case.
